name: MySQL-Sync
version: ${project.version}
main: hd.sphinx.sync.Main
api-version: 1.17
authors: [ Sphinx_HD ]
description: Syncs Player Data between Servers
folia-supported: true
commands:
  sync:
    description: Sync Command
    usage: /sync <args>